# Generated by Django 5.1.3 on 2024-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0023_auditlog_time_till_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
