# Generated by Django 5.1.3 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0024_alter_menuitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='time_till_change',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
