# Generated by Django 5.1.3 on 2024-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0026_auditlog_last_edited_dietaryrestriction_last_edited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
