# Generated by Django 5.1.3 on 2024-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0027_alter_restaurant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietaryrestriction',
            name='name',
            field=models.CharField(blank=True, max_length=99, null=True, unique=True),
        ),
    ]
