# Generated by Django 5.1.3 on 2024-11-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('menus', '0028_alter_dietaryrestriction_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['menu_version'], name='menus_audit_menu_ve_30881a_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['available_from', 'available_until'], name='menus_menu_availab_2acdc4_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['name'], name='menus_menui_name_fcb5c5_idx'),
        ),
        migrations.AddIndex(
            model_name='menuversion',
            index=models.Index(fields=['restaurant', 'version_number'], name='menus_menuv_restaur_bbcd47_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='menus_resta_name_6b141c_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['country', 'city', 'state', 'zip', 'street'], name='menus_resta_country_964088_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name', 'phone', 'email', 'website'], name='menus_resta_name_dcab00_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='menus_user_email_9dc9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username', 'email'], name='menus_user_usernam_ef02c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['country', 'city', 'state', 'zip', 'street'], name='menus_user_country_f5e9c1_idx'),
        ),
    ]
