# Generated by Django 5.1.3 on 2024-11-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0029_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
