-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 19:14:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema menu_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema menu_management_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `menu_management_system` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `menu_management_system` ;

-- -----------------------------------------------------
-- Table `menu_management_system`.`auth_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`django_content_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` (`app_label` ASC, `model` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`auth_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` (`content_type_id` ASC, `codename` ASC) VISIBLE,
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `menu_management_system`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 61
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`auth_group_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` (`group_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `menu_management_system`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `menu_management_system`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(3) NULL DEFAULT NULL,
  `zip` SMALLINT NULL DEFAULT NULL,
  `street` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `menus_user_email_9dc9ad_idx` (`email` ASC) VISIBLE,
  INDEX `menus_user_usernam_ef02c5_idx` (`username` ASC, `email` ASC) VISIBLE,
  INDEX `menus_user_country_f5e9c1_idx` (`country` ASC, `city` ASC, `state` ASC, `zip` ASC, `street` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`django_admin_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` (`content_type_id` ASC) VISIBLE,
  INDEX `django_admin_log_user_id_c564eba6_fk_menus_user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `menu_management_system`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_menus_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `menu_management_system`.`menus_user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 131
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`django_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`django_session`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`),
  INDEX `django_session_expire_date_a5c62663` (`expire_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_restaurant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(3) NULL DEFAULT NULL,
  `zip` SMALLINT NULL DEFAULT NULL,
  `street` VARCHAR(50) NULL DEFAULT NULL,
  `website` VARCHAR(200) NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_restaurant_name_d5529e64_uniq` (`name` ASC) VISIBLE,
  INDEX `menus_resta_name_6b141c_idx` (`name` ASC) VISIBLE,
  INDEX `menus_resta_country_964088_idx` (`country` ASC, `city` ASC, `state` ASC, `zip` ASC, `street` ASC) VISIBLE,
  INDEX `menus_resta_name_dcab00_idx` (`name` ASC, `phone` ASC, `email` ASC, `website` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_menuversion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_menuversion` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `version_number` INT NOT NULL,
  `composite_id` VARCHAR(255) NOT NULL,
  `restaurant_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `composite_id` (`composite_id` ASC) VISIBLE,
  INDEX `menus_menuv_restaur_bbcd47_idx` (`restaurant_id` ASC, `version_number` ASC) VISIBLE,
  CONSTRAINT `menus_menuversion_restaurant_id_688f3c51_fk_menus_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `menu_management_system`.`menus_restaurant` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_auditlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_auditlog` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(99) NULL DEFAULT NULL,
  `other` VARCHAR(99) NULL DEFAULT NULL,
  `phase` VARCHAR(99) NULL DEFAULT NULL,
  `time_registered` DATETIME(6) NULL DEFAULT NULL,
  `menu_version_id` BIGINT NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menus_audit_menu_ve_30881a_idx` (`menu_version_id` ASC) VISIBLE,
  CONSTRAINT `menus_auditlog_menu_version_id_bef77f0f_fk_menus_menuversion_id`
    FOREIGN KEY (`menu_version_id`)
    REFERENCES `menu_management_system`.`menus_menuversion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_dietaryrestriction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_dietaryrestriction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(99) NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_dietaryrestriction_name_e56b1d3d_uniq` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_menu` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `active_status` TINYINT(1) NULL DEFAULT NULL,
  `available_until` DATE NULL DEFAULT NULL,
  `available_from` DATE NULL DEFAULT NULL,
  `menu_file` VARCHAR(100) NULL DEFAULT NULL,
  `restaurant_id` BIGINT NULL DEFAULT NULL,
  `timeUpload` DATETIME(6) NULL DEFAULT NULL,
  `user_id_id` BIGINT NULL DEFAULT NULL,
  `version_id` BIGINT NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menus_menu_user_id_id_87f756a1_fk_menus_user_id` (`user_id_id` ASC) VISIBLE,
  INDEX `menus_menu_version_id_b7b04197_fk_menus_menuversion_id` (`version_id` ASC) VISIBLE,
  INDEX `menus_menu_restaurant_id_fae48d76_fk_menus_restaurant_id` (`restaurant_id` ASC) VISIBLE,
  INDEX `menus_menu_availab_2acdc4_idx` (`available_from` ASC, `available_until` ASC) VISIBLE,
  CONSTRAINT `menus_menu_restaurant_id_fae48d76_fk_menus_restaurant_id`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `menu_management_system`.`menus_restaurant` (`id`),
  CONSTRAINT `menus_menu_user_id_id_87f756a1_fk_menus_user_id`
    FOREIGN KEY (`user_id_id`)
    REFERENCES `menu_management_system`.`menus_user` (`id`),
  CONSTRAINT `menus_menu_version_id_b7b04197_fk_menus_menuversion_id`
    FOREIGN KEY (`version_id`)
    REFERENCES `menu_management_system`.`menus_menuversion` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_menusection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_menusection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(99) NULL DEFAULT NULL,
  `menu_id` BIGINT NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menus_menusection_menu_id_5d8f94b3_fk_menus_menu_id` (`menu_id` ASC) VISIBLE,
  CONSTRAINT `menus_menusection_menu_id_5d8f94b3_fk_menus_menu_id`
    FOREIGN KEY (`menu_id`)
    REFERENCES `menu_management_system`.`menus_menu` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 157
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_menuitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_menuitem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(99) NULL DEFAULT NULL,
  `description` VARCHAR(300) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `currency` VARCHAR(99) NULL DEFAULT NULL,
  `available` TINYINT(1) NULL DEFAULT NULL,
  `menu_section_id` BIGINT NULL DEFAULT NULL,
  `last_edited` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `menus_menuitem_menu_section_id_a2019aee_fk_menus_menusection_id` (`menu_section_id` ASC) VISIBLE,
  INDEX `menus_menui_name_fcb5c5_idx` (`name` ASC) VISIBLE,
  CONSTRAINT `menus_menuitem_menu_section_id_a2019aee_fk_menus_menusection_id`
    FOREIGN KEY (`menu_section_id`)
    REFERENCES `menu_management_system`.`menus_menusection` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 777
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_dietaryrestriction_menu_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_dietaryrestriction_menu_items` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `dietaryrestriction_id` BIGINT NOT NULL,
  `menuitem_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_dietaryrestriction_dietaryrestriction_id_me_00824ddf_uniq` (`dietaryrestriction_id` ASC, `menuitem_id` ASC) VISIBLE,
  INDEX `menus_dietaryrestric_menuitem_id_750317e0_fk_menus_men` (`menuitem_id` ASC) VISIBLE,
  CONSTRAINT `menus_dietaryrestric_dietaryrestriction_i_ee4f6c70_fk_menus_die`
    FOREIGN KEY (`dietaryrestriction_id`)
    REFERENCES `menu_management_system`.`menus_dietaryrestriction` (`id`),
  CONSTRAINT `menus_dietaryrestric_menuitem_id_750317e0_fk_menus_men`
    FOREIGN KEY (`menuitem_id`)
    REFERENCES `menu_management_system`.`menus_menuitem` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_user_groups_user_id_group_id_7a5add7e_uniq` (`user_id` ASC, `group_id` ASC) VISIBLE,
  INDEX `menus_user_groups_group_id_aa114b09_fk_auth_group_id` (`group_id` ASC) VISIBLE,
  CONSTRAINT `menus_user_groups_group_id_aa114b09_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `menu_management_system`.`auth_group` (`id`),
  CONSTRAINT `menus_user_groups_user_id_dcf490dc_fk_menus_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `menu_management_system`.`menus_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `menu_management_system`.`menus_user_user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `menu_management_system`.`menus_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_user_user_permissions_user_id_permission_id_25c9a8a0_uniq` (`user_id` ASC, `permission_id` ASC) VISIBLE,
  INDEX `menus_user_user_perm_permission_id_541cadd4_fk_auth_perm` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `menus_user_user_perm_permission_id_541cadd4_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `menu_management_system`.`auth_permission` (`id`),
  CONSTRAINT `menus_user_user_permissions_user_id_77196b6c_fk_menus_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `menu_management_system`.`menus_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
